#=============================================#
#                 v.1.2.8                     # 
#     𝗠𝗨𝗟𝗧𝗜𝗗𝗘𝗩𝗜𝗖𝗘 𝗪𝗛𝗔𝗧𝗦𝗔𝗣𝗣 𝗨𝗦𝗘𝗥 𝗕𝗢𝗧        #
#                ZAHREELA-MD                  #
#=============================================#
# 
#    * @project_name : ZAHREELA-MD
#    * @author : @zahreela-user
#    * @youtube : Not registered 
#    * @description : ZAHREELA-MD ,A Multi-functional whatsapp bot.
#    * @version 1.2.8
# 
# Don't change this name ! [ /zahreela-user/ ]
# Change from below link, else bot not works!

 

FROM quay.io/suhailtechinfo/suhail-v2
RUN git clone https://github.com/zahreela-official/ZAHREELA-MD /root/zahreela
WORKDIR /root/zahreela/
RUN npm install
EXPOSE 8000
CMD ["npm","start" ] 
